import { Button, Grid, Toolbar, Typography } from "@mui/material";
import { green } from "@mui/material/colors";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import CreateAccount from "../components/create-account";
import Login from "../components/login";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />

        <section
          style={{
            position: "relative",
            color: "white",
            textAlign: "center",
          }}
        >
          {/* <Image
          style={{ height: '50px'}}
          src="/images/intro-bg.jpg"
          // height={144}
          // width={144}
          layout="intrinsic"
          alt="Your Name"
        /> */}
          <img
            src="/images/intro-bg.jpg"
            alt="Your Name"
            style={{ height: "80vh", width: "100%", marginTop: "5px" }}
          />

          <div
            style={{
              color: "green",
              position: "absolute",
              top: "50%",
              left: "50%",
              transform: "translate(-50%, -50%)",
            }}
          >
            <h3>Build your own portfolio in just a few seconds</h3>
          </div>
        </section>

        {/* Features */}
        <section></section>

        {/* Create Account */}
        <section style={{ height: "80vh" }} id="signup">
          <Typography sx={{ fontSize: 30, fontWeight: "bold" }}>
            Share you portfolio with the world today!
          </Typography>

          <Grid container spacing={2}>
            <Grid item xs={0} md={9} lg={6}>
              <Login />
            </Grid>

            <Grid item xs={12} md={3} lg={6}>
              <CreateAccount />
            </Grid>
          </Grid>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
