import { Button, Grid, Toolbar, Typography } from "@mui/material";
import { green } from "@mui/material/colors";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import CreateAccount from "../components/create-account";
import Login from "../components/login";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />

        <section
          style={{
            position: "relative",
            color: "white",
            textAlign: "center",
          }}
        >
          {/* <Image
          style={{ height: '50px'}}
          src="/images/intro-bg.jpg"
          // height={144}
          // width={144}
          layout="intrinsic"
          alt="Your Name"
        /> */}
          <img
            src="/images/intro-bg.jpg"
            alt="Your Name"
            style={{ height: "80vh", width: "100%", marginTop: "5px" }}
          />

          <div
            style={{
              color: "green",
              position: "absolute",
              top: "50%",
              left: "50%",
              transform: "translate(-50%, -50%)",
            }}
          >
            <h3>Build your own portfolio in just a few seconds</h3>
          </div>
        </section>

        {/* Features */}
        <section></section>

        {/* Create Account */}
        <section style={{ height: "80vh" }} id="signup" color="#A49675">
          <Typography sx={{ fontSize: 30, fontWeight: "bold" }} mt={2} textAlign="center">
            Share your potfolio with the world today!
          </Typography>

          <Grid container spacing={2}>
            <Grid item md={6}>
              <Login />
            </Grid>

            <Grid item md={6}>
              <CreateAccount />
            </Grid>
          </Grid>
        </section>

        <section
          className={styles.about}
          style={{ height: "80vh", position: "relative" }}
          id="about"
          color="#A49675"
        >
          <Typography>About Us</Typography>
          <br />

          {/* <div className={styles.layer}></div> */}

          <Grid container spacing={2}>
            <Grid md={6}>
              <img
                src="./images/aboutp-bgp.jpg"
                alt="abcd"
                style={{
                  height: "70vh",
                  marginTop: "5px",
                  marginLeft: "15px",
                  maxWidth: "fit-content",
                }}
                color="#0000"
              />
            </Grid>

            <Grid md={6}>
              <div style={{ margin: "120px" }}>
                <h2>We help you share your portfolio to the world</h2>
                <h1>what's a portfolio?</h1>
                <p>we mentor you to design your own portfolio</p>
                <p>we give you the opportunity to network with your friends</p>
              </div>
            </Grid>
          </Grid>

          <div
            style={{
              color: "black",
              position: "absolute",
              top: "50%",
              left: "50%",
              transform: "translate(-0%, -0%)",
            }}
          ></div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          style={{ height: "80vh" }}
          color="#003F3B"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
