import {
  Avatar,
  Box,
  Button,
  Divider,
  Grid,
  Stack,
  Toolbar,
  Typography,
} from "@mui/material";
import { green } from "@mui/material/colors";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useState, useEffect } from "react";
import CreateAccount from "../../components/create-account";
import DashboardNavbar from "../../components/dashboard-navbar";
import Login from "../../components/login";
import Navbar from "../../components/navbar";
import PortfolioCard from "../../components/portfolio-card";
import styles from "../../styles/Home.module.css";

const Dashboard = () => {
  const [portfolios, setPortfolios] = useState([]);

  useEffect(() => {
    const fetchPortfolios = async () => {
      if (typeof window != "undefined") {
        const user = JSON.parse(localStorage.getItem("user")!) as any;

        const resp = await fetch(`/api/portfolio?user=${user._id}`, {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        });

        const json = await resp.json();
        if (json.success == true) {
          setPortfolios(json.data);
        }
      }
    };

    fetchPortfolios();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DashboardNavbar />

        <Grid container spacing={2}>
          {portfolios.map((item) => (
            <Grid item xs={12} md={4} lg={3}>
              <PortfolioCard portfolio={item} />
            </Grid>
          ))}
        </Grid>

        <Link href="/dashboard/new-portfolio">
          <Box textAlign='center' marginTop="100px">
            <Button variant="contained" color="primary">
              Add Portfolio
            </Button>
          </Box>
        </Link>

      </main>
    </div>
  );
};

export default Dashboard;
