import {
  Avatar,
  Button,
  Divider,
  Grid,
  Stack,
  Toolbar,
  Typography,
} from "@mui/material";
import { green } from "@mui/material/colors";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import CreateAccount from "../../components/create-account";
import Login from "../../components/login";
import Navbar from "../../components/navbar";
import PortfolioCard from "../../components/portfolio-card";
import styles from "../../styles/Home.module.css";

class Dashboard extends React.Component<{}, { portfolios: any[] }> {
  constructor(props: any) {
    super(props);

    this.state = {
      portfolios: [],
    };
    this.fetchPortfolios = this.fetchPortfolios.bind(this);
  }

  componentDidMount() {
    this.fetchPortfolios();
  }

  async fetchPortfolios() {
    if (typeof window != "undefined") {
      const user = JSON.parse(localStorage.getItem("user")!) as any;

      const resp = await fetch(`/api/portfolio?user=${user._id}`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      });

      const json = await resp.json();
      console.log(json);
      if (json.success == true) {
        this.setState({
          portfolios: json.data,
        });
      }
    }
  }

  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Navbar />

          <Avatar alt="Remy Sharp" src="/images/profile-img.jpg" />

          <Grid container spacing={2}>
            {this.state.portfolios.map((item) => (
              <Grid item xs={12} md={4} lg={3}>
                <PortfolioCard portfolio={item} />
              </Grid>
            ))}
          </Grid>

          <Link href="/dashboard/new-portfolio">
            <Button variant="contained" color="primary">
              Add Portfolio
            </Button>
          </Link>
        </main>
      </div>
    );
  }
}

export default Dashboard;
